# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ef132662735fa1db70e6f90aa205883cb01ba1134ca478ec80ba5dfdc7f8157eb02579c761670544b7d932d42db28a2058ee62dc63ba1654c2d49c31716873

test:
  secret_key_base: 58ff2dd8bc8718994f933fcdc488c08bf18f126068a4daae2f07cb60f7cf709fca1bcde718484e8c2f46f234b711fe19cfedbc37aa0755f7badfcb02d28c59c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
